# Generated by Django 2.0.6 on 2018-07-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('site', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=17)),
                ('ext', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
