# Generated by Django 2.0.6 on 2018-07-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20180704_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.FileField(default='documents/avatar.svg', upload_to='documents/'),
        ),
    ]
