# Generated by Django 2.0.6 on 2018-07-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_remove_contact_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.FileField(default='documents/avatar.svg', upload_to='documents/'),
        ),
    ]
