# Generated by Django 2.0.6 on 2018-07-04 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_contact_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='documents/avatar.svg', upload_to='documents/')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.ContactImage'),
        ),
    ]
