# Generated by Django 2.0.6 on 2018-07-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20180704_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactimage',
            name='image',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
