# Generated by Django 2.0.6 on 2018-07-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20180704_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactimage',
            name='image',
            field=models.ImageField(default='documents/avatar.svg', upload_to='documents/'),
        ),
    ]
