# Generated by Django 2.0.6 on 2018-07-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_auto_20180704_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, default='documents/avatar.svg', null=True, upload_to='documents/'),
        ),
    ]
